sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t malistech/curso-docker -f Dockerfile.dev .

script:
  - docker run -e CI=true malistech/curso-docker npm run test
