sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t malistech/cursoDocker -f Dockerfile.dev .

script:
  - docker run -e CI=true malistech/cursoDocker npm run test
